[package]
name = "automaton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
graphviz-rust = "0.6.6"
itertools = "0.11.0"
